[package]
name = "rust-http-framework"
version = "0.1.0"
edition = "2021"

[dependencies]
async-std = "1.12.0"
route-macro-attribute = { path = "./crates/route-macro-attribute" }
http-types = { path = "./crates/http-types" }
routes = { path = "./crates/routes" }

