[package]
name = "basic-usage"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust-http-framework = { path = "../../" }
json = "0.12.4"
